{
    'name' : 'CMA Galib Project',
    'version': '1.0',
    'author': 'Mufti Muntasir Ahmed',
    'category': 'Importer and Agent business in Color',
    'complexity': 'easy',
    'description': "Importer and Agent business in Color",
    'depends': ['sale','purchase'],
    'data': [
        'pi/pi_view.xml',
        'loan/loan_view.xml',
        'pi/purchase_inher.xml',
        'pi/pending_pi_history.xml',
        'pi/cancel_pi.xml',
        'pi/convert_to_pi_list.xml',
        'pi/po_pending_list.xml',
        'pi/add_service_view.xml',
    ],
    'installable': True,
    'auto_install': False,
}
