{
    'name' : 'CMA Galib Project',
    'version': '1.0',
    'author': 'Mufti Muntasir Ahmed',
    'category': 'Importer and Agent business in Color',
    'complexity': 'easy',
    'description': "Importer and Agent business in Color",
    'depends': ['sale','purchase'],
    'data': [
        'pi/pi_view.xml',
        'loan/loan_view.xml',
        'loan/add_loan_receipt_view.xml',
        'pi/purchase_inher.xml',
        # 'pi/pending_pi_history.xml',
        # 'pi/cancel_pi.xml',
        # 'pi/convert_to_pi_list.xml',
        # 'pi/po_pending_list.xml',
        'pi/add_service_view.xml',
        'pi/pi_payment_view.xml',
        # 'pi/report/proforma_report_menu.xml',
        # 'pi/report/report_proforma.xml',
        # 'loan/add_service_loan_view.xml',
        # 'loan/cancel_loan.xml',
        # 'loan/return_loan.xml',
        # 'loan/so_converted.xml',
        # 'loan/loan_report/loan_report_menu.xml',
        # 'loan/loan_report/report_loan.xml'
    ],
    'installable': True,
    'auto_install': False,
}
